<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1828
// Last edited in MyBB Editor by : Matty Wjeisz
// Last edited date : Sat, 18 Jun 2022 13:16:42 +0000
// --------------------------------------------------------------------------------

$l['avatarep_user_profile'] = 'View Profile';
$l['avatarep_user_messages'] = 'View Messages';
$l['avatarep_user_sendpm'] = 'Send PM';
$l['avatarep_user_sendemail'] = 'Send E-mail';
$l['avatarep_user_threads'] = 'View Threads';
$l['avatarep_user_error'] = ' Error ';
$l['avatarep_user_error_text'] = ' You must login to see this content ';
$l['avatarep_user_alt'] = '{1}';
$l['avatarep_user_no_avatar'] = 'No avatar';
$l['avatarep_retrieving'] = 'Retrieving Data';
$l['avatarep_loading'] = 'Loading...';
