services:
  mysql:
    build:
      context: ./docker/mysql
    container_name: mybb_mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      mybb_network:
        ipv4_address: 172.28.1.2
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      start_interval: 3s
      interval: 10s
      timeout: 5s
      retries: 3

  mybb:
    container_name: mybb_forum
    build:
      context: ./docker/mybb
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html:rw
      - ./stylesheets:/var/stylesheets:ro
      - ./templates:/var/templates:ro
    networks:
      - mybb_network
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mybb_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    networks:
      - mybb_network
    depends_on:
      - mysql

networks:
  mybb_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16