-- liquibase formatted sql

-- changeset liquibase:1737903523367-1
CREATE TABLE mybb_adminlog (uid INT UNSIGNED DEFAULT 0 NOT NULL, ipaddress VARBINARY(16) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, module VARCHAR(50) DEFAULT '' NOT NULL, action VARCHAR(50) DEFAULT '' NOT NULL, data TEXT NOT NULL);

-- changeset liquibase:1737903523367-2
CREATE TABLE mybb_adminoptions (uid INT DEFAULT 0 NOT NULL, cpstyle VARCHAR(50) DEFAULT '' NOT NULL, cplanguage VARCHAR(50) DEFAULT '' NOT NULL, codepress TINYINT(1) DEFAULT 1 NOT NULL, notes TEXT NOT NULL, permissions TEXT NOT NULL, defaultviews TEXT NOT NULL, loginattempts SMALLINT UNSIGNED DEFAULT 0 NOT NULL, loginlockoutexpiry INT UNSIGNED DEFAULT 0 NOT NULL, authsecret VARCHAR(16) DEFAULT '' NOT NULL, recovery_codes VARCHAR(177) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_ADMINOPTIONS PRIMARY KEY (uid));

-- changeset liquibase:1737903523367-3
CREATE TABLE mybb_adminsessions (sid VARCHAR(32) DEFAULT '' NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, loginkey VARCHAR(50) DEFAULT '' NOT NULL, ip VARBINARY(16) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, lastactive INT UNSIGNED DEFAULT 0 NOT NULL, data TEXT NOT NULL, useragent VARCHAR(200) DEFAULT '' NOT NULL, authenticated TINYINT(1) DEFAULT 0 NOT NULL);

-- changeset liquibase:1737903523367-4
CREATE TABLE mybb_adminviews (vid INT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, title VARCHAR(100) DEFAULT '' NOT NULL, type VARCHAR(6) DEFAULT '' NOT NULL, visibility TINYINT(1) DEFAULT 0 NOT NULL, fields TEXT NOT NULL, conditions TEXT NOT NULL, custom_profile_fields TEXT NOT NULL, sortby VARCHAR(20) DEFAULT '' NOT NULL, sortorder VARCHAR(4) DEFAULT '' NOT NULL, perpage SMALLINT UNSIGNED DEFAULT 0 NOT NULL, view_type VARCHAR(6) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_ADMINVIEWS PRIMARY KEY (vid));

-- changeset liquibase:1737903523367-5
CREATE TABLE mybb_announcements (aid INT UNSIGNED AUTO_INCREMENT NOT NULL, fid INT DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, subject VARCHAR(120) DEFAULT '' NOT NULL, message TEXT NOT NULL, startdate INT UNSIGNED DEFAULT 0 NOT NULL, enddate INT UNSIGNED DEFAULT 0 NOT NULL, allowhtml TINYINT(1) DEFAULT 0 NOT NULL, allowmycode TINYINT(1) DEFAULT 0 NOT NULL, allowsmilies TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_ANNOUNCEMENTS PRIMARY KEY (aid));

-- changeset liquibase:1737903523367-6
CREATE TABLE mybb_attachments (aid INT UNSIGNED AUTO_INCREMENT NOT NULL, pid INT UNSIGNED DEFAULT 0 NOT NULL, posthash VARCHAR(50) DEFAULT '' NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, filename VARCHAR(255) DEFAULT '' NOT NULL, filetype VARCHAR(120) DEFAULT '' NOT NULL, filesize INT UNSIGNED DEFAULT 0 NOT NULL, attachname VARCHAR(255) DEFAULT '' NOT NULL, downloads INT UNSIGNED DEFAULT 0 NOT NULL, dateuploaded INT UNSIGNED DEFAULT 0 NOT NULL, `visible` TINYINT(1) DEFAULT 0 NOT NULL, thumbnail VARCHAR(120) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_ATTACHMENTS PRIMARY KEY (aid));

-- changeset liquibase:1737903523367-7
CREATE TABLE mybb_attachtypes (atid INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT '' NOT NULL, mimetype VARCHAR(120) DEFAULT '' NOT NULL, extension VARCHAR(10) DEFAULT '' NOT NULL, maxsize INT UNSIGNED DEFAULT 0 NOT NULL, icon VARCHAR(100) DEFAULT '' NOT NULL, enabled TINYINT(1) DEFAULT 1 NOT NULL, forcedownload TINYINT(1) DEFAULT 0 NOT NULL, `groups` TEXT NOT NULL, forums TEXT NOT NULL, avatarfile TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_ATTACHTYPES PRIMARY KEY (atid));

-- changeset liquibase:1737903523367-8
CREATE TABLE mybb_awaitingactivation (aid INT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, code VARCHAR(100) DEFAULT '' NOT NULL, type CHAR(1) DEFAULT '' NOT NULL, validated TINYINT(1) DEFAULT 0 NOT NULL, misc VARCHAR(255) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_AWAITINGACTIVATION PRIMARY KEY (aid));

-- changeset liquibase:1737903523367-9
CREATE TABLE mybb_badwords (bid INT UNSIGNED AUTO_INCREMENT NOT NULL, badword VARCHAR(100) DEFAULT '' NOT NULL, regex TINYINT(1) DEFAULT 0 NOT NULL, replacement VARCHAR(100) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_BADWORDS PRIMARY KEY (bid));

-- changeset liquibase:1737903523367-10
CREATE TABLE mybb_banfilters (fid INT UNSIGNED AUTO_INCREMENT NOT NULL, filter VARCHAR(200) DEFAULT '' NOT NULL, type TINYINT(1) DEFAULT 0 NOT NULL, lastuse INT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_BANFILTERS PRIMARY KEY (fid));

-- changeset liquibase:1737903523367-11
CREATE TABLE mybb_banned (uid INT UNSIGNED DEFAULT 0 NOT NULL, gid INT UNSIGNED DEFAULT 0 NOT NULL, oldgroup INT UNSIGNED DEFAULT 0 NOT NULL, oldadditionalgroups TEXT NOT NULL, olddisplaygroup INT UNSIGNED DEFAULT 0 NOT NULL, `admin` INT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, bantime VARCHAR(50) DEFAULT '' NOT NULL, lifted INT UNSIGNED DEFAULT 0 NOT NULL, reason VARCHAR(255) DEFAULT '' NOT NULL);

-- changeset liquibase:1737903523367-12
CREATE TABLE mybb_buddyrequests (id INT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, touid INT UNSIGNED DEFAULT 0 NOT NULL, date INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_BUDDYREQUESTS PRIMARY KEY (id));

-- changeset liquibase:1737903523367-13
CREATE TABLE mybb_calendarpermissions (cid INT UNSIGNED DEFAULT 0 NOT NULL, gid INT UNSIGNED DEFAULT 0 NOT NULL, canviewcalendar TINYINT(1) DEFAULT 0 NOT NULL, canaddevents TINYINT(1) DEFAULT 0 NOT NULL, canbypasseventmod TINYINT(1) DEFAULT 0 NOT NULL, canmoderateevents TINYINT(1) DEFAULT 0 NOT NULL);

-- changeset liquibase:1737903523367-14
CREATE TABLE mybb_calendars (cid INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(100) DEFAULT '' NOT NULL, disporder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, startofweek TINYINT(1) DEFAULT 0 NOT NULL, showbirthdays TINYINT(1) DEFAULT 0 NOT NULL, eventlimit SMALLINT UNSIGNED DEFAULT 0 NOT NULL, moderation TINYINT(1) DEFAULT 0 NOT NULL, allowhtml TINYINT(1) DEFAULT 0 NOT NULL, allowmycode TINYINT(1) DEFAULT 0 NOT NULL, allowimgcode TINYINT(1) DEFAULT 0 NOT NULL, allowvideocode TINYINT(1) DEFAULT 0 NOT NULL, allowsmilies TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_CALENDARS PRIMARY KEY (cid));

-- changeset liquibase:1737903523367-15
CREATE TABLE mybb_captcha (imagehash VARCHAR(32) DEFAULT '' NOT NULL, imagestring VARCHAR(8) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, used TINYINT(1) DEFAULT 0 NOT NULL);

-- changeset liquibase:1737903523367-16
CREATE TABLE mybb_datacache (title VARCHAR(50) DEFAULT '' NOT NULL, cache MEDIUMTEXT NOT NULL, CONSTRAINT PK_MYBB_DATACACHE PRIMARY KEY (title));

-- changeset liquibase:1737903523367-17
CREATE TABLE mybb_delayedmoderation (did INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(30) DEFAULT '' NOT NULL, delaydateline INT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, fid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, tids TEXT NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, inputs TEXT NOT NULL, CONSTRAINT PK_MYBB_DELAYEDMODERATION PRIMARY KEY (did));

-- changeset liquibase:1737903523367-18
CREATE TABLE mybb_events (eid INT UNSIGNED AUTO_INCREMENT NOT NULL, cid INT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, name VARCHAR(120) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, `visible` TINYINT(1) DEFAULT 0 NOT NULL, private TINYINT(1) DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, starttime INT UNSIGNED DEFAULT 0 NOT NULL, endtime INT UNSIGNED DEFAULT 0 NOT NULL, timezone VARCHAR(5) DEFAULT '' NOT NULL, ignoretimezone TINYINT(1) DEFAULT 0 NOT NULL, usingtime TINYINT(1) DEFAULT 0 NOT NULL, repeats TEXT NOT NULL, CONSTRAINT PK_MYBB_EVENTS PRIMARY KEY (eid));

-- changeset liquibase:1737903523367-19
CREATE TABLE mybb_forumpermissions (pid INT UNSIGNED AUTO_INCREMENT NOT NULL, fid INT UNSIGNED DEFAULT 0 NOT NULL, gid INT UNSIGNED DEFAULT 0 NOT NULL, canview TINYINT(1) DEFAULT 0 NOT NULL, canviewthreads TINYINT(1) DEFAULT 0 NOT NULL, canonlyviewownthreads TINYINT(1) DEFAULT 0 NOT NULL, candlattachments TINYINT(1) DEFAULT 0 NOT NULL, canpostthreads TINYINT(1) DEFAULT 0 NOT NULL, canpostreplys TINYINT(1) DEFAULT 0 NOT NULL, canonlyreplyownthreads TINYINT(1) DEFAULT 0 NOT NULL, canpostattachments TINYINT(1) DEFAULT 0 NOT NULL, canratethreads TINYINT(1) DEFAULT 0 NOT NULL, caneditposts TINYINT(1) DEFAULT 0 NOT NULL, candeleteposts TINYINT(1) DEFAULT 0 NOT NULL, candeletethreads TINYINT(1) DEFAULT 0 NOT NULL, caneditattachments TINYINT(1) DEFAULT 0 NOT NULL, canviewdeletionnotice TINYINT(1) DEFAULT 0 NOT NULL, modposts TINYINT(1) DEFAULT 0 NOT NULL, modthreads TINYINT(1) DEFAULT 0 NOT NULL, mod_edit_posts TINYINT(1) DEFAULT 0 NOT NULL, modattachments TINYINT(1) DEFAULT 0 NOT NULL, canpostpolls TINYINT(1) DEFAULT 0 NOT NULL, canvotepolls TINYINT(1) DEFAULT 0 NOT NULL, cansearch TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_FORUMPERMISSIONS PRIMARY KEY (pid));

-- changeset liquibase:1737903523367-20
CREATE TABLE mybb_forums (fid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, linkto VARCHAR(180) DEFAULT '' NOT NULL, type CHAR(1) DEFAULT '' NOT NULL, pid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, parentlist TEXT NOT NULL, disporder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, active TINYINT(1) DEFAULT 0 NOT NULL, open TINYINT(1) DEFAULT 0 NOT NULL, threads INT UNSIGNED DEFAULT 0 NOT NULL, posts INT UNSIGNED DEFAULT 0 NOT NULL, lastpost INT UNSIGNED DEFAULT 0 NOT NULL, lastposter VARCHAR(120) DEFAULT '' NOT NULL, lastposteruid INT UNSIGNED DEFAULT 0 NOT NULL, lastposttid INT UNSIGNED DEFAULT 0 NOT NULL, lastpostsubject VARCHAR(120) DEFAULT '' NOT NULL, allowhtml TINYINT(1) DEFAULT 0 NOT NULL, allowmycode TINYINT(1) DEFAULT 0 NOT NULL, allowsmilies TINYINT(1) DEFAULT 0 NOT NULL, allowimgcode TINYINT(1) DEFAULT 0 NOT NULL, allowvideocode TINYINT(1) DEFAULT 0 NOT NULL, allowpicons TINYINT(1) DEFAULT 0 NOT NULL, allowtratings TINYINT(1) DEFAULT 0 NOT NULL, usepostcounts TINYINT(1) DEFAULT 0 NOT NULL, usethreadcounts TINYINT(1) DEFAULT 0 NOT NULL, requireprefix TINYINT(1) DEFAULT 0 NOT NULL, password VARCHAR(50) DEFAULT '' NOT NULL, showinjump TINYINT(1) DEFAULT 0 NOT NULL, style SMALLINT UNSIGNED DEFAULT 0 NOT NULL, overridestyle TINYINT(1) DEFAULT 0 NOT NULL, rulestype TINYINT(1) DEFAULT 0 NOT NULL, rulestitle VARCHAR(200) DEFAULT '' NOT NULL, rules TEXT NOT NULL, unapprovedthreads INT UNSIGNED DEFAULT 0 NOT NULL, unapprovedposts INT UNSIGNED DEFAULT 0 NOT NULL, deletedthreads INT UNSIGNED DEFAULT 0 NOT NULL, deletedposts INT UNSIGNED DEFAULT 0 NOT NULL, defaultdatecut SMALLINT UNSIGNED DEFAULT 0 NOT NULL, defaultsortby VARCHAR(10) DEFAULT '' NOT NULL, defaultsortorder VARCHAR(4) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_FORUMS PRIMARY KEY (fid));

-- changeset liquibase:1737903523367-21
CREATE TABLE mybb_forumsread (fid INT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL);

-- changeset liquibase:1737903523367-22
CREATE TABLE mybb_forumsubscriptions (fsid INT UNSIGNED AUTO_INCREMENT NOT NULL, fid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_FORUMSUBSCRIPTIONS PRIMARY KEY (fsid));

-- changeset liquibase:1737903523367-23
CREATE TABLE mybb_groupleaders (lid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, gid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, canmanagemembers TINYINT(1) DEFAULT 0 NOT NULL, canmanagerequests TINYINT(1) DEFAULT 0 NOT NULL, caninvitemembers TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_GROUPLEADERS PRIMARY KEY (lid));

-- changeset liquibase:1737903523367-24
CREATE TABLE mybb_helpdocs (hid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, sid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, name VARCHAR(120) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, document TEXT NOT NULL, usetranslation TINYINT(1) DEFAULT 0 NOT NULL, enabled TINYINT(1) DEFAULT 0 NOT NULL, disporder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_HELPDOCS PRIMARY KEY (hid));

-- changeset liquibase:1737903523367-25
CREATE TABLE mybb_helpsections (sid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, usetranslation TINYINT(1) DEFAULT 0 NOT NULL, enabled TINYINT(1) DEFAULT 0 NOT NULL, disporder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_HELPSECTIONS PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-26
CREATE TABLE mybb_hidecontent (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT NOT NULL, pid BIGINT NOT NULL, CONSTRAINT PK_MYBB_HIDECONTENT PRIMARY KEY (id));

-- changeset liquibase:1737903523367-27
CREATE TABLE mybb_icons (iid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT '' NOT NULL, `path` VARCHAR(220) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_ICONS PRIMARY KEY (iid));

-- changeset liquibase:1737903523367-28
CREATE TABLE mybb_joinrequests (rid INT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, gid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, reason VARCHAR(250) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, invite TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_JOINREQUESTS PRIMARY KEY (rid));

-- changeset liquibase:1737903523367-29
CREATE TABLE mybb_mailerrors (eid INT UNSIGNED AUTO_INCREMENT NOT NULL, subject VARCHAR(200) DEFAULT '' NOT NULL, message TEXT NOT NULL, toaddress VARCHAR(150) DEFAULT '' NOT NULL, fromaddress VARCHAR(150) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, error TEXT NOT NULL, smtperror VARCHAR(200) DEFAULT '' NOT NULL, smtpcode SMALLINT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_MAILERRORS PRIMARY KEY (eid));

-- changeset liquibase:1737903523367-30
CREATE TABLE mybb_maillogs (mid INT UNSIGNED AUTO_INCREMENT NOT NULL, subject VARCHAR(200) DEFAULT '' NOT NULL, message TEXT NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, fromuid INT UNSIGNED DEFAULT 0 NOT NULL, fromemail VARCHAR(200) DEFAULT '' NOT NULL, touid INT UNSIGNED DEFAULT 0 NOT NULL, toemail VARCHAR(200) DEFAULT '' NOT NULL, tid INT UNSIGNED DEFAULT 0 NOT NULL, ipaddress VARBINARY(16) DEFAULT '' NOT NULL, type TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_MAILLOGS PRIMARY KEY (mid));

-- changeset liquibase:1737903523367-31
CREATE TABLE mybb_mailqueue (mid INT UNSIGNED AUTO_INCREMENT NOT NULL, mailto VARCHAR(200) NOT NULL, mailfrom VARCHAR(200) NOT NULL, subject VARCHAR(200) NOT NULL, message TEXT NOT NULL, headers TEXT NOT NULL, CONSTRAINT PK_MYBB_MAILQUEUE PRIMARY KEY (mid));

-- changeset liquibase:1737903523367-32
CREATE TABLE mybb_massemails (mid INT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, subject VARCHAR(200) DEFAULT '' NOT NULL, message TEXT NOT NULL, htmlmessage TEXT NOT NULL, type TINYINT(1) DEFAULT 0 NOT NULL, format TINYINT(1) DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, senddate INT UNSIGNED DEFAULT 0 NOT NULL, status TINYINT(1) DEFAULT 0 NOT NULL, sentcount INT UNSIGNED DEFAULT 0 NOT NULL, totalcount INT UNSIGNED DEFAULT 0 NOT NULL, conditions TEXT NOT NULL, perpage SMALLINT UNSIGNED DEFAULT 50 NOT NULL, CONSTRAINT PK_MYBB_MASSEMAILS PRIMARY KEY (mid));

-- changeset liquibase:1737903523367-33
CREATE TABLE mybb_moderatorlog (uid INT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, fid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, tid INT UNSIGNED DEFAULT 0 NOT NULL, pid INT UNSIGNED DEFAULT 0 NOT NULL, action TEXT NOT NULL, data TEXT NOT NULL, ipaddress VARBINARY(16) DEFAULT '' NOT NULL);

-- changeset liquibase:1737903523367-34
CREATE TABLE mybb_moderators (mid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, fid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, id INT UNSIGNED DEFAULT 0 NOT NULL, isgroup TINYINT(1) DEFAULT 0 NOT NULL, caneditposts TINYINT(1) DEFAULT 0 NOT NULL, cansoftdeleteposts TINYINT(1) DEFAULT 0 NOT NULL, canrestoreposts TINYINT(1) DEFAULT 0 NOT NULL, candeleteposts TINYINT(1) DEFAULT 0 NOT NULL, cansoftdeletethreads TINYINT(1) DEFAULT 0 NOT NULL, canrestorethreads TINYINT(1) DEFAULT 0 NOT NULL, candeletethreads TINYINT(1) DEFAULT 0 NOT NULL, canviewips TINYINT(1) DEFAULT 0 NOT NULL, canviewunapprove TINYINT(1) DEFAULT 0 NOT NULL, canviewdeleted TINYINT(1) DEFAULT 0 NOT NULL, canopenclosethreads TINYINT(1) DEFAULT 0 NOT NULL, canstickunstickthreads TINYINT(1) DEFAULT 0 NOT NULL, canapproveunapprovethreads TINYINT(1) DEFAULT 0 NOT NULL, canapproveunapproveposts TINYINT(1) DEFAULT 0 NOT NULL, canapproveunapproveattachs TINYINT(1) DEFAULT 0 NOT NULL, canmanagethreads TINYINT(1) DEFAULT 0 NOT NULL, canmanagepolls TINYINT(1) DEFAULT 0 NOT NULL, canpostclosedthreads TINYINT(1) DEFAULT 0 NOT NULL, canmovetononmodforum TINYINT(1) DEFAULT 0 NOT NULL, canusecustomtools TINYINT(1) DEFAULT 0 NOT NULL, canmanageannouncements TINYINT(1) DEFAULT 0 NOT NULL, canmanagereportedposts TINYINT(1) DEFAULT 0 NOT NULL, canviewmodlog TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_MODERATORS PRIMARY KEY (mid));

-- changeset liquibase:1737903523367-35
CREATE TABLE mybb_modtools (tid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(200) NOT NULL, `description` TEXT NOT NULL, forums TEXT NOT NULL, `groups` TEXT NOT NULL, type CHAR(1) DEFAULT '' NOT NULL, postoptions TEXT NOT NULL, threadoptions TEXT NOT NULL, CONSTRAINT PK_MYBB_MODTOOLS PRIMARY KEY (tid));

-- changeset liquibase:1737903523367-36
CREATE TABLE mybb_mycode (cid INT UNSIGNED AUTO_INCREMENT NOT NULL, title VARCHAR(100) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, regex TEXT NOT NULL, replacement TEXT NOT NULL, active TINYINT(1) DEFAULT 0 NOT NULL, parseorder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_MYCODE PRIMARY KEY (cid));

-- changeset liquibase:1737903523367-37
CREATE TABLE mybb_polls (pid INT UNSIGNED AUTO_INCREMENT NOT NULL, tid INT UNSIGNED DEFAULT 0 NOT NULL, question VARCHAR(200) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, options TEXT NOT NULL, votes TEXT NOT NULL, numoptions SMALLINT UNSIGNED DEFAULT 0 NOT NULL, numvotes INT UNSIGNED DEFAULT 0 NOT NULL, timeout INT UNSIGNED DEFAULT 0 NOT NULL, closed TINYINT(1) DEFAULT 0 NOT NULL, multiple TINYINT(1) DEFAULT 0 NOT NULL, public TINYINT(1) DEFAULT 0 NOT NULL, maxoptions SMALLINT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_POLLS PRIMARY KEY (pid));

-- changeset liquibase:1737903523367-38
CREATE TABLE mybb_pollvotes (vid INT UNSIGNED AUTO_INCREMENT NOT NULL, pid INT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, voteoption SMALLINT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, ipaddress VARBINARY(16) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_POLLVOTES PRIMARY KEY (vid));

-- changeset liquibase:1737903523367-39
CREATE TABLE mybb_posts (pid INT UNSIGNED AUTO_INCREMENT NOT NULL, tid INT UNSIGNED DEFAULT 0 NOT NULL, replyto INT UNSIGNED DEFAULT 0 NOT NULL, fid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, subject VARCHAR(120) DEFAULT '' NOT NULL, icon SMALLINT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, username VARCHAR(80) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, message TEXT NOT NULL, ipaddress VARBINARY(16) DEFAULT '' NOT NULL, includesig TINYINT(1) DEFAULT 0 NOT NULL, smilieoff TINYINT(1) DEFAULT 0 NOT NULL, edituid INT UNSIGNED DEFAULT 0 NOT NULL, edittime INT UNSIGNED DEFAULT 0 NOT NULL, editreason VARCHAR(150) DEFAULT '' NOT NULL, `visible` TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_POSTS PRIMARY KEY (pid));

-- changeset liquibase:1737903523367-40
CREATE TABLE mybb_privatemessages (pmid INT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, toid INT UNSIGNED DEFAULT 0 NOT NULL, fromid INT UNSIGNED DEFAULT 0 NOT NULL, recipients TEXT NOT NULL, folder SMALLINT UNSIGNED DEFAULT 1 NOT NULL, subject VARCHAR(120) DEFAULT '' NOT NULL, icon SMALLINT UNSIGNED DEFAULT 0 NOT NULL, message TEXT NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, deletetime INT UNSIGNED DEFAULT 0 NOT NULL, status TINYINT(1) DEFAULT 0 NOT NULL, statustime INT UNSIGNED DEFAULT 0 NOT NULL, includesig TINYINT(1) DEFAULT 0 NOT NULL, smilieoff TINYINT(1) DEFAULT 0 NOT NULL, receipt TINYINT(1) DEFAULT 0 NOT NULL, readtime INT UNSIGNED DEFAULT 0 NOT NULL, ipaddress VARBINARY(16) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_PRIVATEMESSAGES PRIMARY KEY (pmid));

-- changeset liquibase:1737903523367-41
CREATE TABLE mybb_profilefields (fid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(100) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, disporder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, type TEXT NOT NULL, regex TEXT NOT NULL, length SMALLINT UNSIGNED DEFAULT 0 NOT NULL, maxlength SMALLINT UNSIGNED DEFAULT 0 NOT NULL, required TINYINT(1) DEFAULT 0 NOT NULL, registration TINYINT(1) DEFAULT 0 NOT NULL, profile TINYINT(1) DEFAULT 0 NOT NULL, postbit TINYINT(1) DEFAULT 0 NOT NULL, viewableby TEXT NOT NULL, editableby TEXT NOT NULL, postnum SMALLINT UNSIGNED DEFAULT 0 NOT NULL, allowhtml TINYINT(1) DEFAULT 0 NOT NULL, allowmycode TINYINT(1) DEFAULT 0 NOT NULL, allowsmilies TINYINT(1) DEFAULT 0 NOT NULL, allowimgcode TINYINT(1) DEFAULT 0 NOT NULL, allowvideocode TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_PROFILEFIELDS PRIMARY KEY (fid));

-- changeset liquibase:1737903523367-42
CREATE TABLE mybb_promotionlogs (plid INT UNSIGNED AUTO_INCREMENT NOT NULL, pid INT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, oldusergroup VARCHAR(200) DEFAULT '0' NOT NULL, newusergroup SMALLINT DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, type VARCHAR(9) DEFAULT 'primary' NOT NULL, CONSTRAINT PK_MYBB_PROMOTIONLOGS PRIMARY KEY (plid));

-- changeset liquibase:1737903523367-43
CREATE TABLE mybb_promotions (pid INT UNSIGNED AUTO_INCREMENT NOT NULL, title VARCHAR(120) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, enabled TINYINT(1) DEFAULT 1 NOT NULL, logging TINYINT(1) DEFAULT 0 NOT NULL, posts INT UNSIGNED DEFAULT 0 NOT NULL, posttype CHAR(2) DEFAULT '' NOT NULL, threads INT UNSIGNED DEFAULT 0 NOT NULL, threadtype CHAR(2) DEFAULT '' NOT NULL, registered INT UNSIGNED DEFAULT 0 NOT NULL, registeredtype VARCHAR(20) DEFAULT '' NOT NULL, online INT UNSIGNED DEFAULT 0 NOT NULL, onlinetype VARCHAR(20) DEFAULT '' NOT NULL, reputations INT DEFAULT 0 NOT NULL, reputationtype CHAR(2) DEFAULT '' NOT NULL, referrals INT UNSIGNED DEFAULT 0 NOT NULL, referralstype CHAR(2) DEFAULT '' NOT NULL, warnings INT UNSIGNED DEFAULT 0 NOT NULL, warningstype CHAR(2) DEFAULT '' NOT NULL, requirements VARCHAR(200) DEFAULT '' NOT NULL, originalusergroup VARCHAR(120) DEFAULT '0' NOT NULL, newusergroup SMALLINT UNSIGNED DEFAULT 0 NOT NULL, usergrouptype VARCHAR(120) DEFAULT '0' NOT NULL, CONSTRAINT PK_MYBB_PROMOTIONS PRIMARY KEY (pid));

-- changeset liquibase:1737903523367-44
CREATE TABLE mybb_questions (qid INT UNSIGNED AUTO_INCREMENT NOT NULL, question VARCHAR(200) DEFAULT '' NOT NULL, answer VARCHAR(150) DEFAULT '' NOT NULL, shown INT UNSIGNED DEFAULT 0 NOT NULL, correct INT UNSIGNED DEFAULT 0 NOT NULL, incorrect INT UNSIGNED DEFAULT 0 NOT NULL, active TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_QUESTIONS PRIMARY KEY (qid));

-- changeset liquibase:1737903523367-45
CREATE TABLE mybb_questionsessions (sid VARCHAR(32) DEFAULT '' NOT NULL, qid INT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_QUESTIONSESSIONS PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-46
CREATE TABLE mybb_reportedcontent (rid INT UNSIGNED AUTO_INCREMENT NOT NULL, id INT UNSIGNED DEFAULT 0 NOT NULL, id2 INT UNSIGNED DEFAULT 0 NOT NULL, id3 INT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, reportstatus TINYINT(1) DEFAULT 0 NOT NULL, reasonid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, reason VARCHAR(250) DEFAULT '' NOT NULL, type VARCHAR(50) DEFAULT '' NOT NULL, reports INT UNSIGNED DEFAULT 0 NOT NULL, reporters TEXT NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, lastreport INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_REPORTEDCONTENT PRIMARY KEY (rid));

-- changeset liquibase:1737903523367-47
CREATE TABLE mybb_reportreasons (rid INT UNSIGNED AUTO_INCREMENT NOT NULL, title VARCHAR(250) DEFAULT '' NOT NULL, appliesto VARCHAR(250) DEFAULT '' NOT NULL, extra TINYINT(1) DEFAULT 0 NOT NULL, disporder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_REPORTREASONS PRIMARY KEY (rid));

-- changeset liquibase:1737903523367-48
CREATE TABLE mybb_reputation (rid INT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, adduid INT UNSIGNED DEFAULT 0 NOT NULL, pid INT UNSIGNED DEFAULT 0 NOT NULL, reputation SMALLINT DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, comments TEXT NOT NULL, CONSTRAINT PK_MYBB_REPUTATION PRIMARY KEY (rid));

-- changeset liquibase:1737903523367-49
CREATE TABLE mybb_searchlog (sid VARCHAR(32) DEFAULT '' NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, ipaddress VARBINARY(16) DEFAULT '' NOT NULL, threads LONGTEXT NOT NULL, posts LONGTEXT NOT NULL, resulttype VARCHAR(10) DEFAULT '' NOT NULL, querycache TEXT NOT NULL, keywords TEXT NOT NULL, CONSTRAINT PK_MYBB_SEARCHLOG PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-50
CREATE TABLE mybb_sessions (sid VARCHAR(32) DEFAULT '' NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, ip VARBINARY(16) DEFAULT '' NOT NULL, time INT UNSIGNED DEFAULT 0 NOT NULL, location VARCHAR(150) DEFAULT '' NOT NULL, useragent VARCHAR(200) DEFAULT '' NOT NULL, anonymous TINYINT(1) DEFAULT 0 NOT NULL, nopermission TINYINT(1) DEFAULT 0 NOT NULL, location1 INT UNSIGNED DEFAULT 0 NOT NULL, location2 INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_SESSIONS PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-51
CREATE TABLE mybb_settinggroups (gid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(100) DEFAULT '' NOT NULL, title VARCHAR(220) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, disporder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, isdefault TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_SETTINGGROUPS PRIMARY KEY (gid));

-- changeset liquibase:1737903523367-52
CREATE TABLE mybb_settings (sid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT '' NOT NULL, title VARCHAR(120) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, optionscode TEXT NOT NULL, value TEXT NOT NULL, disporder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, gid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, isdefault TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_SETTINGS PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-53
CREATE TABLE mybb_smilies (sid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT '' NOT NULL, find TEXT NOT NULL, image VARCHAR(220) DEFAULT '' NOT NULL, disporder SMALLINT UNSIGNED DEFAULT 0 NOT NULL, showclickable TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_SMILIES PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-54
CREATE TABLE mybb_spamlog (sid INT UNSIGNED AUTO_INCREMENT NOT NULL, username VARCHAR(120) DEFAULT '' NOT NULL, email VARCHAR(220) DEFAULT '' NOT NULL, ipaddress VARBINARY(16) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, data TEXT NOT NULL, CONSTRAINT PK_MYBB_SPAMLOG PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-55
CREATE TABLE mybb_spiders (sid INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(100) DEFAULT '' NOT NULL, theme SMALLINT UNSIGNED DEFAULT 0 NOT NULL, language VARCHAR(20) DEFAULT '' NOT NULL, usergroup SMALLINT UNSIGNED DEFAULT 0 NOT NULL, useragent VARCHAR(200) DEFAULT '' NOT NULL, lastvisit INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_SPIDERS PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-56
CREATE TABLE mybb_stats (dateline INT UNSIGNED DEFAULT 0 NOT NULL, numusers INT UNSIGNED DEFAULT 0 NOT NULL, numthreads INT UNSIGNED DEFAULT 0 NOT NULL, numposts INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_STATS PRIMARY KEY (dateline));

-- changeset liquibase:1737903523367-57
CREATE TABLE mybb_tasklog (lid INT UNSIGNED AUTO_INCREMENT NOT NULL, tid INT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, data TEXT NOT NULL, CONSTRAINT PK_MYBB_TASKLOG PRIMARY KEY (lid));

-- changeset liquibase:1737903523367-58
CREATE TABLE mybb_tasks (tid INT UNSIGNED AUTO_INCREMENT NOT NULL, title VARCHAR(120) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, file VARCHAR(30) DEFAULT '' NOT NULL, minute VARCHAR(200) DEFAULT '' NOT NULL, hour VARCHAR(200) DEFAULT '' NOT NULL, day VARCHAR(100) DEFAULT '' NOT NULL, month VARCHAR(30) DEFAULT '' NOT NULL, weekday VARCHAR(15) DEFAULT '' NOT NULL, nextrun INT UNSIGNED DEFAULT 0 NOT NULL, lastrun INT UNSIGNED DEFAULT 0 NOT NULL, enabled TINYINT(1) DEFAULT 1 NOT NULL, logging TINYINT(1) DEFAULT 0 NOT NULL, `locked` INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_TASKS PRIMARY KEY (tid));

-- changeset liquibase:1737903523367-59
CREATE TABLE mybb_templategroups (gid INT UNSIGNED AUTO_INCREMENT NOT NULL, prefix VARCHAR(50) DEFAULT '' NOT NULL, title VARCHAR(100) DEFAULT '' NOT NULL, isdefault TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_TEMPLATEGROUPS PRIMARY KEY (gid));

-- changeset liquibase:1737903523367-60
CREATE TABLE mybb_templates (tid INT UNSIGNED AUTO_INCREMENT NOT NULL, title VARCHAR(120) DEFAULT '' NOT NULL, template TEXT NOT NULL, sid SMALLINT DEFAULT 0 NOT NULL, version VARCHAR(20) DEFAULT '0' NOT NULL, status VARCHAR(10) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_TEMPLATES PRIMARY KEY (tid));

-- changeset liquibase:1737903523367-61
CREATE TABLE mybb_templatesets (sid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, title VARCHAR(120) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_TEMPLATESETS PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-62
CREATE TABLE mybb_themes (tid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(100) DEFAULT '' NOT NULL, pid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, def TINYINT(1) DEFAULT 0 NOT NULL, properties TEXT NOT NULL, stylesheets TEXT NOT NULL, allowedgroups TEXT NOT NULL, CONSTRAINT PK_MYBB_THEMES PRIMARY KEY (tid));

-- changeset liquibase:1737903523367-63
CREATE TABLE mybb_themestylesheets (sid INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(30) DEFAULT '' NOT NULL, tid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, attachedto TEXT NOT NULL, stylesheet LONGTEXT NOT NULL, cachefile VARCHAR(100) DEFAULT '' NOT NULL, lastmodified INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_THEMESTYLESHEETS PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-64
CREATE TABLE mybb_threadprefixes (pid INT UNSIGNED AUTO_INCREMENT NOT NULL, prefix VARCHAR(120) DEFAULT '' NOT NULL, displaystyle VARCHAR(200) DEFAULT '' NOT NULL, forums TEXT NOT NULL, `groups` TEXT NOT NULL, CONSTRAINT PK_MYBB_THREADPREFIXES PRIMARY KEY (pid));

-- changeset liquibase:1737903523367-65
CREATE TABLE mybb_threadratings (rid INT UNSIGNED AUTO_INCREMENT NOT NULL, tid INT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, rating TINYINT(1) DEFAULT 0 NOT NULL, ipaddress VARBINARY(16) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_THREADRATINGS PRIMARY KEY (rid));

-- changeset liquibase:1737903523367-66
CREATE TABLE mybb_threads (tid INT UNSIGNED AUTO_INCREMENT NOT NULL, fid SMALLINT UNSIGNED DEFAULT 0 NOT NULL, subject VARCHAR(120) DEFAULT '' NOT NULL, prefix SMALLINT UNSIGNED DEFAULT 0 NOT NULL, icon SMALLINT UNSIGNED DEFAULT 0 NOT NULL, poll INT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, username VARCHAR(80) DEFAULT '' NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, firstpost INT UNSIGNED DEFAULT 0 NOT NULL, lastpost INT UNSIGNED DEFAULT 0 NOT NULL, lastposter VARCHAR(120) DEFAULT '' NOT NULL, lastposteruid INT UNSIGNED DEFAULT 0 NOT NULL, views INT UNSIGNED DEFAULT 0 NOT NULL, replies INT UNSIGNED DEFAULT 0 NOT NULL, closed VARCHAR(30) DEFAULT '' NOT NULL, sticky TINYINT(1) DEFAULT 0 NOT NULL, numratings SMALLINT UNSIGNED DEFAULT 0 NOT NULL, totalratings SMALLINT UNSIGNED DEFAULT 0 NOT NULL, notes TEXT NOT NULL, `visible` TINYINT(1) DEFAULT 0 NOT NULL, unapprovedposts INT UNSIGNED DEFAULT 0 NOT NULL, deletedposts INT UNSIGNED DEFAULT 0 NOT NULL, attachmentcount INT UNSIGNED DEFAULT 0 NOT NULL, deletetime INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_THREADS PRIMARY KEY (tid));

-- changeset liquibase:1737903523367-67
CREATE TABLE mybb_threadsread (tid INT UNSIGNED DEFAULT 0 NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL);

-- changeset liquibase:1737903523367-68
CREATE TABLE mybb_threadsubscriptions (sid INT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, tid INT UNSIGNED DEFAULT 0 NOT NULL, notification TINYINT(1) DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_THREADSUBSCRIPTIONS PRIMARY KEY (sid));

-- changeset liquibase:1737903523367-69
CREATE TABLE mybb_threadviews (tid INT UNSIGNED DEFAULT 0 NOT NULL);

-- changeset liquibase:1737903523367-70
CREATE TABLE mybb_userfields (ufid INT UNSIGNED DEFAULT 0 NOT NULL, fid1 TEXT NOT NULL, fid2 TEXT NOT NULL, fid3 TEXT NOT NULL, fid4 TEXT NULL, fid5 TEXT NULL, CONSTRAINT PK_MYBB_USERFIELDS PRIMARY KEY (ufid));

-- changeset liquibase:1737903523367-71
CREATE TABLE mybb_usergroups (gid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, type TINYINT(1) DEFAULT 2 NOT NULL, title VARCHAR(120) DEFAULT '' NOT NULL, `description` TEXT NOT NULL, namestyle VARCHAR(200) DEFAULT '{username}' NOT NULL, usertitle VARCHAR(120) DEFAULT '' NOT NULL, stars SMALLINT UNSIGNED DEFAULT 0 NOT NULL, starimage VARCHAR(120) DEFAULT '' NOT NULL, image VARCHAR(120) DEFAULT '' NOT NULL, disporder SMALLINT UNSIGNED NOT NULL, isbannedgroup TINYINT(1) DEFAULT 0 NOT NULL, canview TINYINT(1) DEFAULT 0 NOT NULL, canviewthreads TINYINT(1) DEFAULT 0 NOT NULL, canviewprofiles TINYINT(1) DEFAULT 0 NOT NULL, candlattachments TINYINT(1) DEFAULT 0 NOT NULL, canviewboardclosed TINYINT(1) DEFAULT 0 NOT NULL, canpostthreads TINYINT(1) DEFAULT 0 NOT NULL, canpostreplys TINYINT(1) DEFAULT 0 NOT NULL, canpostattachments TINYINT(1) DEFAULT 0 NOT NULL, canratethreads TINYINT(1) DEFAULT 0 NOT NULL, modposts TINYINT(1) DEFAULT 0 NOT NULL, modthreads TINYINT(1) DEFAULT 0 NOT NULL, mod_edit_posts TINYINT(1) DEFAULT 0 NOT NULL, modattachments TINYINT(1) DEFAULT 0 NOT NULL, caneditposts TINYINT(1) DEFAULT 0 NOT NULL, candeleteposts TINYINT(1) DEFAULT 0 NOT NULL, candeletethreads TINYINT(1) DEFAULT 0 NOT NULL, caneditattachments TINYINT(1) DEFAULT 0 NOT NULL, canviewdeletionnotice TINYINT(1) DEFAULT 0 NOT NULL, canpostpolls TINYINT(1) DEFAULT 0 NOT NULL, canvotepolls TINYINT(1) DEFAULT 0 NOT NULL, canundovotes TINYINT(1) DEFAULT 0 NOT NULL, canusepms TINYINT(1) DEFAULT 0 NOT NULL, cansendpms TINYINT(1) DEFAULT 0 NOT NULL, cantrackpms TINYINT(1) DEFAULT 0 NOT NULL, candenypmreceipts TINYINT(1) DEFAULT 0 NOT NULL, pmquota INT UNSIGNED DEFAULT 0 NOT NULL, maxpmrecipients INT UNSIGNED DEFAULT 5 NOT NULL, cansendemail TINYINT(1) DEFAULT 0 NOT NULL, cansendemailoverride TINYINT(1) DEFAULT 0 NOT NULL, maxemails INT UNSIGNED DEFAULT 5 NOT NULL, emailfloodtime INT UNSIGNED DEFAULT 5 NOT NULL, canviewmemberlist TINYINT(1) DEFAULT 0 NOT NULL, canviewcalendar TINYINT(1) DEFAULT 0 NOT NULL, canaddevents TINYINT(1) DEFAULT 0 NOT NULL, canbypasseventmod TINYINT(1) DEFAULT 0 NOT NULL, canmoderateevents TINYINT(1) DEFAULT 0 NOT NULL, canviewonline TINYINT(1) DEFAULT 0 NOT NULL, canviewwolinvis TINYINT(1) DEFAULT 0 NOT NULL, canviewonlineips TINYINT(1) DEFAULT 0 NOT NULL, cancp TINYINT(1) DEFAULT 0 NOT NULL, issupermod TINYINT(1) DEFAULT 0 NOT NULL, cansearch TINYINT(1) DEFAULT 0 NOT NULL, canusercp TINYINT(1) DEFAULT 0 NOT NULL, canuploadavatars TINYINT(1) DEFAULT 0 NOT NULL, canratemembers TINYINT(1) DEFAULT 0 NOT NULL, canchangename TINYINT(1) DEFAULT 0 NOT NULL, canbereported TINYINT(1) DEFAULT 0 NOT NULL, canbeinvisible TINYINT(1) DEFAULT 1 NOT NULL, canchangewebsite TINYINT(1) DEFAULT 1 NOT NULL, showforumteam TINYINT(1) DEFAULT 0 NOT NULL, usereputationsystem TINYINT(1) DEFAULT 0 NOT NULL, cangivereputations TINYINT(1) DEFAULT 0 NOT NULL, candeletereputations TINYINT(1) DEFAULT 0 NOT NULL, reputationpower INT UNSIGNED DEFAULT 0 NOT NULL, maxreputationsday INT UNSIGNED DEFAULT 0 NOT NULL, maxreputationsperuser INT UNSIGNED DEFAULT 0 NOT NULL, maxreputationsperthread INT UNSIGNED DEFAULT 0 NOT NULL, candisplaygroup TINYINT(1) DEFAULT 0 NOT NULL, attachquota INT UNSIGNED DEFAULT 0 NOT NULL, cancustomtitle TINYINT(1) DEFAULT 0 NOT NULL, canwarnusers TINYINT(1) DEFAULT 0 NOT NULL, canreceivewarnings TINYINT(1) DEFAULT 0 NOT NULL, maxwarningsday INT UNSIGNED DEFAULT 3 NOT NULL, canmodcp TINYINT(1) DEFAULT 0 NOT NULL, showinbirthdaylist TINYINT(1) DEFAULT 0 NOT NULL, canoverridepm TINYINT(1) DEFAULT 0 NOT NULL, canusesig TINYINT(1) DEFAULT 0 NOT NULL, canusesigxposts SMALLINT UNSIGNED DEFAULT 0 NOT NULL, signofollow TINYINT(1) DEFAULT 0 NOT NULL, edittimelimit INT UNSIGNED DEFAULT 0 NOT NULL, maxposts INT UNSIGNED DEFAULT 0 NOT NULL, showmemberlist TINYINT(1) DEFAULT 1 NOT NULL, canmanageannounce TINYINT(1) DEFAULT 0 NOT NULL, canmanagemodqueue TINYINT(1) DEFAULT 0 NOT NULL, canmanagereportedcontent TINYINT(1) DEFAULT 0 NOT NULL, canviewmodlogs TINYINT(1) DEFAULT 0 NOT NULL, caneditprofiles TINYINT(1) DEFAULT 0 NOT NULL, canbanusers TINYINT(1) DEFAULT 0 NOT NULL, canviewwarnlogs TINYINT(1) DEFAULT 0 NOT NULL, canuseipsearch TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_USERGROUPS PRIMARY KEY (gid));

-- changeset liquibase:1737903523367-72
CREATE TABLE mybb_users (uid INT UNSIGNED AUTO_INCREMENT NOT NULL, username VARCHAR(120) DEFAULT '' NOT NULL, password VARCHAR(120) DEFAULT '' NOT NULL, salt VARCHAR(10) DEFAULT '' NOT NULL, loginkey VARCHAR(50) DEFAULT '' NOT NULL, email VARCHAR(220) DEFAULT '' NOT NULL, postnum INT UNSIGNED DEFAULT 0 NOT NULL, threadnum INT UNSIGNED DEFAULT 0 NOT NULL, avatar VARCHAR(200) DEFAULT '' NOT NULL, avatardimensions VARCHAR(10) DEFAULT '' NOT NULL, avatartype VARCHAR(10) DEFAULT '0' NOT NULL, usergroup SMALLINT UNSIGNED DEFAULT 0 NOT NULL, additionalgroups VARCHAR(200) DEFAULT '' NOT NULL, displaygroup SMALLINT UNSIGNED DEFAULT 0 NOT NULL, usertitle VARCHAR(250) DEFAULT '' NOT NULL, regdate INT UNSIGNED DEFAULT 0 NOT NULL, lastactive INT UNSIGNED DEFAULT 0 NOT NULL, lastvisit INT UNSIGNED DEFAULT 0 NOT NULL, lastpost INT UNSIGNED DEFAULT 0 NOT NULL, website VARCHAR(200) DEFAULT '' NOT NULL, icq VARCHAR(10) DEFAULT '' NOT NULL, skype VARCHAR(75) DEFAULT '' NOT NULL, google VARCHAR(75) DEFAULT '' NOT NULL, birthday VARCHAR(15) DEFAULT '' NOT NULL, birthdayprivacy VARCHAR(4) DEFAULT 'all' NOT NULL, signature TEXT NOT NULL, allownotices TINYINT(1) DEFAULT 0 NOT NULL, hideemail TINYINT(1) DEFAULT 0 NOT NULL, subscriptionmethod TINYINT(1) DEFAULT 0 NOT NULL, `invisible` TINYINT(1) DEFAULT 0 NOT NULL, receivepms TINYINT(1) DEFAULT 0 NOT NULL, receivefrombuddy TINYINT(1) DEFAULT 0 NOT NULL, pmnotice TINYINT(1) DEFAULT 0 NOT NULL, pmnotify TINYINT(1) DEFAULT 0 NOT NULL, buddyrequestspm TINYINT(1) DEFAULT 1 NOT NULL, buddyrequestsauto TINYINT(1) DEFAULT 0 NOT NULL, threadmode VARCHAR(8) DEFAULT '' NOT NULL, showimages TINYINT(1) DEFAULT 0 NOT NULL, showvideos TINYINT(1) DEFAULT 0 NOT NULL, showsigs TINYINT(1) DEFAULT 0 NOT NULL, showavatars TINYINT(1) DEFAULT 0 NOT NULL, showquickreply TINYINT(1) DEFAULT 0 NOT NULL, showredirect TINYINT(1) DEFAULT 0 NOT NULL, ppp SMALLINT UNSIGNED DEFAULT 0 NOT NULL, tpp SMALLINT UNSIGNED DEFAULT 0 NOT NULL, daysprune SMALLINT UNSIGNED DEFAULT 0 NOT NULL, dateformat VARCHAR(4) DEFAULT '' NOT NULL, timeformat VARCHAR(4) DEFAULT '' NOT NULL, timezone VARCHAR(5) DEFAULT '' NOT NULL, dst TINYINT(1) DEFAULT 0 NOT NULL, dstcorrection TINYINT(1) DEFAULT 0 NOT NULL, buddylist TEXT NOT NULL, ignorelist TEXT NOT NULL, style SMALLINT UNSIGNED DEFAULT 0 NOT NULL, away TINYINT(1) DEFAULT 0 NOT NULL, awaydate INT UNSIGNED DEFAULT 0 NOT NULL, returndate VARCHAR(15) DEFAULT '' NOT NULL, awayreason VARCHAR(200) DEFAULT '' NOT NULL, pmfolders TEXT NOT NULL, notepad TEXT NOT NULL, referrer INT UNSIGNED DEFAULT 0 NOT NULL, referrals INT UNSIGNED DEFAULT 0 NOT NULL, reputation INT DEFAULT 0 NOT NULL, regip VARBINARY(16) DEFAULT '' NOT NULL, lastip VARBINARY(16) DEFAULT '' NOT NULL, language VARCHAR(50) DEFAULT '' NOT NULL, timeonline INT UNSIGNED DEFAULT 0 NOT NULL, showcodebuttons TINYINT(1) DEFAULT 1 NOT NULL, totalpms INT UNSIGNED DEFAULT 0 NOT NULL, unreadpms INT UNSIGNED DEFAULT 0 NOT NULL, warningpoints INT UNSIGNED DEFAULT 0 NOT NULL, moderateposts TINYINT(1) DEFAULT 0 NOT NULL, moderationtime INT UNSIGNED DEFAULT 0 NOT NULL, suspendposting TINYINT(1) DEFAULT 0 NOT NULL, suspensiontime INT UNSIGNED DEFAULT 0 NOT NULL, suspendsignature TINYINT(1) DEFAULT 0 NOT NULL, suspendsigtime INT UNSIGNED DEFAULT 0 NOT NULL, coppauser TINYINT(1) DEFAULT 0 NOT NULL, loginattempts SMALLINT UNSIGNED DEFAULT 0 NOT NULL, loginlockoutexpiry INT UNSIGNED DEFAULT 0 NOT NULL, usernotes TEXT NOT NULL, sourceeditor TINYINT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_USERS PRIMARY KEY (uid), UNIQUE (username));

-- changeset liquibase:1737903523367-73
CREATE TABLE mybb_usertitles (utid SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, posts INT UNSIGNED DEFAULT 0 NOT NULL, title VARCHAR(250) DEFAULT '' NOT NULL, stars SMALLINT UNSIGNED DEFAULT 0 NOT NULL, starimage VARCHAR(120) DEFAULT '' NOT NULL, CONSTRAINT PK_MYBB_USERTITLES PRIMARY KEY (utid));

-- changeset liquibase:1737903523367-74
CREATE TABLE mybb_warninglevels (lid INT UNSIGNED AUTO_INCREMENT NOT NULL, percentage SMALLINT UNSIGNED DEFAULT 0 NOT NULL, action TEXT NOT NULL, CONSTRAINT PK_MYBB_WARNINGLEVELS PRIMARY KEY (lid));

-- changeset liquibase:1737903523367-75
CREATE TABLE mybb_warnings (wid INT UNSIGNED AUTO_INCREMENT NOT NULL, uid INT UNSIGNED DEFAULT 0 NOT NULL, tid INT UNSIGNED DEFAULT 0 NOT NULL, pid INT UNSIGNED DEFAULT 0 NOT NULL, title VARCHAR(120) DEFAULT '' NOT NULL, points SMALLINT UNSIGNED DEFAULT 0 NOT NULL, dateline INT UNSIGNED DEFAULT 0 NOT NULL, issuedby INT UNSIGNED DEFAULT 0 NOT NULL, expires INT UNSIGNED DEFAULT 0 NOT NULL, expired TINYINT(1) DEFAULT 0 NOT NULL, daterevoked INT UNSIGNED DEFAULT 0 NOT NULL, revokedby INT UNSIGNED DEFAULT 0 NOT NULL, revokereason TEXT NOT NULL, notes TEXT NOT NULL, CONSTRAINT PK_MYBB_WARNINGS PRIMARY KEY (wid));

-- changeset liquibase:1737903523367-76
CREATE TABLE mybb_warningtypes (tid INT UNSIGNED AUTO_INCREMENT NOT NULL, title VARCHAR(120) DEFAULT '' NOT NULL, points SMALLINT UNSIGNED DEFAULT 0 NOT NULL, expirationtime INT UNSIGNED DEFAULT 0 NOT NULL, CONSTRAINT PK_MYBB_WARNINGTYPES PRIMARY KEY (tid));

-- changeset liquibase:1737903523367-77
ALTER TABLE mybb_forumsread ADD CONSTRAINT fid UNIQUE (fid, uid);

-- changeset liquibase:1737903523367-78
ALTER TABLE mybb_threadsread ADD CONSTRAINT tid UNIQUE (tid, uid);

-- changeset liquibase:1737903523367-79
CREATE INDEX cid ON mybb_events(cid);

-- changeset liquibase:1737903523367-80
CREATE INDEX dateline ON mybb_banned(dateline);

-- changeset liquibase:1737903523367-81
CREATE INDEX dateline ON mybb_captcha(dateline);

-- changeset liquibase:1737903523367-82
CREATE INDEX dateline ON mybb_forumsread(dateline);

-- changeset liquibase:1737903523367-83
CREATE INDEX dateline ON mybb_posts(dateline);

-- changeset liquibase:1737903523367-84
CREATE INDEX dateline ON mybb_threads(dateline);

-- changeset liquibase:1737903523367-85
CREATE INDEX dateline ON mybb_threadsread(dateline);

-- changeset liquibase:1737903523367-86
CREATE INDEX daterange ON mybb_events(starttime, endtime);

-- changeset liquibase:1737903523367-87
CREATE INDEX fid ON mybb_announcements(fid);

-- changeset liquibase:1737903523367-88
CREATE INDEX fid ON mybb_forumpermissions(fid, gid);

-- changeset liquibase:1737903523367-89
CREATE INDEX fid ON mybb_moderatorlog(fid);

-- changeset liquibase:1737903523367-90
CREATE INDEX fid ON mybb_threads(fid, `visible`, sticky);

-- changeset liquibase:1737903523367-91
CREATE INDEX firstpost ON mybb_threads(firstpost);

-- changeset liquibase:1737903523367-92
CREATE INDEX gid ON mybb_settings(gid);

-- changeset liquibase:1737903523367-93
CREATE INDEX imagehash ON mybb_captcha(imagehash);

-- changeset liquibase:1737903523367-94
CREATE INDEX ip ON mybb_sessions(ip);

-- changeset liquibase:1737903523367-95
CREATE INDEX ipaddress ON mybb_posts(ipaddress);

-- changeset liquibase:1737903523367-96
CREATE INDEX lastip ON mybb_users(lastip);

-- changeset liquibase:1737903523367-97
CREATE INDEX lastpost ON mybb_threads(lastpost, fid);

-- changeset liquibase:1737903523367-98
CREATE INDEX lastreport ON mybb_reportedcontent(lastreport);

-- changeset liquibase:1737903523367-99
CREATE INDEX location ON mybb_sessions(location1, location2);

-- changeset liquibase:1737903523367-100
CREATE INDEX message ON mybb_posts(message);

-- changeset liquibase:1737903523367-101
CREATE INDEX module ON mybb_adminlog(module, action);

-- changeset liquibase:1737903523367-102
CREATE INDEX pid ON mybb_attachments(pid, `visible`);

-- changeset liquibase:1737903523367-103
CREATE INDEX pid ON mybb_hidecontent(pid);

-- changeset liquibase:1737903523367-104
CREATE INDEX pid ON mybb_pollvotes(pid, uid);

-- changeset liquibase:1737903523367-105
CREATE INDEX private ON mybb_events(private);

-- changeset liquibase:1737903523367-106
CREATE INDEX regip ON mybb_users(regip);

-- changeset liquibase:1737903523367-107
CREATE INDEX reportstatus ON mybb_reportedcontent(reportstatus);

-- changeset liquibase:1737903523367-108
CREATE INDEX sid ON mybb_templates(sid, title);

-- changeset liquibase:1737903523367-109
CREATE INDEX subject ON mybb_threads(subject);

-- changeset liquibase:1737903523367-110
CREATE INDEX tid ON mybb_moderatorlog(tid);

-- changeset liquibase:1737903523367-111
CREATE INDEX tid ON mybb_polls(tid);

-- changeset liquibase:1737903523367-112
CREATE INDEX tid ON mybb_posts(tid, uid);

-- changeset liquibase:1737903523367-113
CREATE INDEX tid ON mybb_themestylesheets(tid);

-- changeset liquibase:1737903523367-114
CREATE INDEX tid ON mybb_threadratings(tid, uid);

-- changeset liquibase:1737903523367-115
CREATE INDEX tid ON mybb_threadsubscriptions(tid, notification);

-- changeset liquibase:1737903523367-116
CREATE INDEX tid ON mybb_threadviews(tid);

-- changeset liquibase:1737903523367-117
CREATE INDEX tiddate ON mybb_posts(tid, dateline);

-- changeset liquibase:1737903523367-118
CREATE INDEX time ON mybb_sessions(time);

-- changeset liquibase:1737903523367-119
CREATE INDEX toid ON mybb_privatemessages(toid);

-- changeset liquibase:1737903523367-120
CREATE INDEX touid ON mybb_buddyrequests(touid);

-- changeset liquibase:1737903523367-121
CREATE INDEX type ON mybb_banfilters(type);

-- changeset liquibase:1737903523367-122
CREATE INDEX uid ON mybb_adminlog(uid);

-- changeset liquibase:1737903523367-123
CREATE INDEX uid ON mybb_attachments(uid);

-- changeset liquibase:1737903523367-124
CREATE INDEX uid ON mybb_banned(uid);

-- changeset liquibase:1737903523367-125
CREATE INDEX uid ON mybb_buddyrequests(uid);

-- changeset liquibase:1737903523367-126
CREATE INDEX uid ON mybb_forumsubscriptions(uid);

-- changeset liquibase:1737903523367-127
CREATE INDEX uid ON mybb_hidecontent(uid);

-- changeset liquibase:1737903523367-128
CREATE INDEX uid ON mybb_moderatorlog(uid);

-- changeset liquibase:1737903523367-129
CREATE INDEX uid ON mybb_moderators(id, fid);

-- changeset liquibase:1737903523367-130
CREATE INDEX uid ON mybb_posts(uid);

-- changeset liquibase:1737903523367-131
CREATE INDEX uid ON mybb_privatemessages(uid, folder);

-- changeset liquibase:1737903523367-132
CREATE INDEX uid ON mybb_reputation(uid);

-- changeset liquibase:1737903523367-133
CREATE INDEX uid ON mybb_sessions(uid);

-- changeset liquibase:1737903523367-134
CREATE INDEX uid ON mybb_threads(uid);

-- changeset liquibase:1737903523367-135
CREATE INDEX uid ON mybb_threadsubscriptions(uid);

-- changeset liquibase:1737903523367-136
CREATE INDEX uid ON mybb_warnings(uid);

-- changeset liquibase:1737903523367-137
CREATE INDEX usergroup ON mybb_users(usergroup);

-- changeset liquibase:1737903523367-138
CREATE INDEX `visible` ON mybb_posts(`visible`);

