name: Bug
description: Report an issue
title: "[BUG]"
labels: ["bug"]
projects: ["MysteriousGreenBean/projects/4"]
body:
  - type: textarea
    id: bug
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug here
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen
    validations:
      required: true
    
