FROM mariadb:latest

ENV MARIADB_ROOT_PASSWORD=root
ENV MARIADB_DATABASE=crystalforum_

RUN apt-get update && apt-get install -y python3-pip && \
    pip3 install mysql-replication
COPY ./init.sql /docker-entrypoint-initdb.d/
COPY my.cnf /etc/mysql/my.cnf
RUN chmod 644 /etc/mysql/my.cnf