name: Assign issue to project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.ISSUE_MANAGEMENT_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Crystalforum Project
    steps:
    - name: Assign NEW issues and NEW pull requests to Crystalforum project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/users/MysteriousGreenBean/projects/4'
