name: Set Issue Status to Backlog

on:
  issues:
    types: [opened]

jobs:
  update_status:
    runs-on: ubuntu-latest

    steps:
    - name: Set issue status to "Backlog" in the project
      env:
        GITHUB_TOKEN: ${{ secrets.ISSUE_MANAGEMENT_TOKEN }}
      run: |
        issue_number=${{ github.event.issue.number }}
        owner=${{ github.repository_owner }}
        repo_name=${{ github.event.repository.name }}
        project_id="PVT_kwHOALga5M4AmCpx"

        project_item_id=$(gh api graphql -f query='
             query {
                node(id: "'"$project_id"'") {
                  ... on ProjectV2 {
                    items(first: 5, orderBy: { field: POSITION, direction: DESC}) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            number
                          }
                        }
                      }
                    }
                  }
                }
              }' -q ".data.node.items.nodes[] | select(.content.number == \"$issue_number\") | .id")

          # Set the status of the issue to "Backlog"
          gh api graphql -f query='
          mutation {
            updateProjectV2ItemFieldValue(input:{
              fieldId: "'"PVT_kwHOALga5M4AmCpx"'"
              itemId: "'"$issue_node_id"'"
              projectId:"'"$project_id"'"
              value:{singleSelectOptionId: "'"f75ad846"'"}}) {
              projectV2Item {
                id    
              }
            }
          } '

