name: Set Issue Status to Backlog

on:
  issues:
    types: [opened]

jobs:
  update_status:
    runs-on: ubuntu-latest

    steps:
    - name: Set issue status to "Backlog" in the project
      env:
        GITHUB_TOKEN: ${{ secrets.ISSUE_MANAGEMENT_TOKEN }}
      run: |
        issue_number=${{ github.event.issue.number }}
        owner=${{ github.repository_owner }}
        repo_name=${{ github.event.repository.name }}
        project_id="PVT_kwHOALga5M4AmCpx"

        echo "Moving issue $issue_number to Backlog"

        project_item_id=$(gh api graphql -F project_id=$project_id -f query="
             query($project_id: ID!) {
                node(id: $project_id) {
                  ... on ProjectV2 {
                    items(first: 5, orderBy: { field: POSITION, direction: DESC}) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            number
                          }
                        }
                      }
                    }
                  }
                }
              }" -q ".data.node.items.nodes[] | select(.content.number == $issue_number) | .id")


          echo "Project Item ID: $project_item_id"
          
          # Set the status of the issue to "Backlog"
          gh api graphql -F project_item_id=$project_item_id  -F project_id=$project_id -f query="
          mutation($project_item_id: ID!, $project_id: ID!) {
            updateProjectV2ItemFieldValue(input:{
              fieldId: \"PVTSSF_lAHOALga5M4AmCpxzgeAE6M\"
              itemId: $project_item_id
              projectId: $project_id
              value:{singleSelectOptionId: \"f75ad846\"}}) {
              projectV2Item {
                id    
              }
            }
          } "